# -*- mode: python ; coding: utf-8 -*-
import os

block_cipher = None

a = Analysis(
    ['src/main.py'],
    pathex=[os.getcwd()],
    binaries=[],
    datas=[
        ('assets', 'assets') if os.path.exists('assets') else None,
    ],
    hiddenimports=[
        # GUI and theming
        'tkinter',
        'tkinter.ttk',
        'tkinter.messagebox',
        'sv_ttk',
        'darkdetect',
        'notify-py',
        'playsound3',

        # Networking and automation
        'aiohttp',
        'loguru',
        'pydantic',
        'watchdog',
        'cryptography.fernet',
        'playwright',
        'playwright.async_api',
        'playwright._impl',
        'playwright._impl._api_structures',
        'playwright._impl._browser_type',
        'playwright._impl._browser',
        'playwright._impl._browser_context',
        'playwright._impl._page',
        'playwright._impl._locator',
        'playwright._impl._element_handle',
        'playwright._impl._js_handle',
        'playwright._impl._network',
        'playwright._impl._cdp_session',
        'playwright._impl._connection',
        'playwright._impl._transport',
        'playwright._impl._helper',
        'playwright._impl._errors',
        'playwright._impl._wait_helper',
        'playwright._impl._frame',
        'playwright._impl._worker',
        'playwright._impl._accessibility',
        'playwright._impl._file_chooser',
        'playwright._impl._keyboard',
        'playwright._impl._mouse',
        'playwright._impl._touchscreen',
        'playwright._impl._video',
        'playwright._impl._web_socket',
        'playwright._impl._console_message',
        'playwright._impl._dialog',
        'playwright._impl._download',
        'playwright._impl._request',
        'playwright._impl._response',
        'playwright._impl._route',
        'playwright._impl._timeout_settings',
        'playwright._impl._utils',
        'playwright._impl._path_utils',
        'playwright._impl._api_generator',
        'playwright._impl._generator',
        'playwright._impl._driver',
        'playwright._impl._browser_type_impl',
        'playwright._impl._browser_impl',
        'playwright._impl._browser_context_impl',
        'playwright._impl._page_impl',
        'playwright._impl._locator_impl',
        'playwright._impl._element_handle_impl',
        'playwright._impl._js_handle_impl',
        'playwright._impl._network_impl',
        'playwright._impl._cdp_session_impl',
        'playwright._impl._connection_impl',
        'playwright._impl._transport_impl',
        'playwright._impl._helper_impl',
        'playwright._impl._errors_impl',
        'playwright._impl._wait_helper_impl',
        'playwright._impl._frame_impl',
        'playwright._impl._worker_impl',
        'playwright._impl._accessibility_impl',
        'playwright._impl._file_chooser_impl',
        'playwright._impl._keyboard_impl',
        'playwright._impl._mouse_impl',
        'playwright._impl._touchscreen_impl',
        'playwright._impl._video_impl',
        'playwright._impl._web_socket_impl',
        'playwright._impl._console_message_impl',
        'playwright._impl._dialog_impl',
        'playwright._impl._download_impl',
        'playwright._impl._request_impl',
        'playwright._impl._response_impl',
        'playwright._impl._route_impl',
        'playwright._impl._timeout_settings_impl',
        'playwright._impl._utils_impl',
        'playwright._impl._path_utils_impl',
        'playwright._impl._api_generator_impl',
        'playwright._impl._generator_impl',
        'playwright._impl._driver_impl',
        'random-user-agent',
        'browser_use',
        'browser_use.browser',
        'browser_use.browser.types',
        'browser_use.browser.context',
        'browser_use.agent',
        'browser_use.agent.service',
        'browser_use.controller',
        'browser_use.controller.service',
        'browser_use.dom',
        'browser_use.dom.service',

        # HTTP client libraries (required by browser_use and langchain)
        'httpx',
        'httpcore',
        'requests',
        'requests.auth',
        'requests.sessions',
        'requests.models',
        'requests.adapters',

        # Project modules (explicit to help PyInstaller discovery)
        'src.main',

        'src.infrastructure',
        'src.infrastructure.logger',
        'src.infrastructure.client',
        'src.infrastructure.client.fco',

        'src.gui',
        'src.gui.fco',
        'src.gui.accounts_tab',
        'src.gui.activity_log_tab',
        'src.gui.notification_icon',

        'src.services',
        'src.services.fco',
        'src.services.login_handler',
        'src.services.websocket_handler',

        'src.schemas',
        'src.schemas.configs',
        'src.schemas.billboard',
        'src.schemas.spin_response',
        'src.schemas.user_response',
        'src.schemas.enum',
        'src.schemas.enum.account_tag',
        'src.schemas.enum.message_tab',

        'src.utils',
        'src.utils.configs',
        'src.utils.contants',
        'src.utils.files',
        'src.utils.methods',
        'src.utils.platforms',
        'src.utils.requests',
        'src.utils.sounds',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'matplotlib',
        'numpy',
        'scipy',
        'pandas',
        'jupyter',
        'notebook',
        'IPython',
        'selenium',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

# Filter out None values from datas
a.datas = [item for item in a.datas if item is not None]

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    version='version_info.txt',
    name='FC_Online_Tool',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='assets/icon.ico' if os.path.exists('assets/icon.ico') else None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name='FC_Online_Tool'
)
